# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Ornithe Properties
# check these on https://ornithemc.net/develop/
minecraft_version=in-20100223
feather_mappings=22
loader_version=0.28.1
clientOnly=true

# Mod Properties
mod_version=1.0
maven_group=com.mclegoman
archives_base_name=fleecifer

# Dependencies
