org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

mod_version = 1.2.2
maven_group = com.mclegoman
archives_name = fleecifer
enabled_platforms = quilt,fabric,neoforge

minecraft_version = 1.21.5

quilt_loader_version = 0.29.0-beta.5
fabric_loader_version = 0.16.13
neoforge_version = 21.5.55-beta

fabric_api_version=0.121.0+1.21.5