modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/MCLegoMan/fleecifer/issues"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "fleecifer"
version = "${version}"
displayName = "Fleecifer"
displayURL = "https://github.com/MCLegoMan/fleecifer"
logoFile = "icon.png"
authors = "MCLegoMan"
description = '''Turns sheep hostile...'''

[[dependencies.fleecifer]]
modId = "neoforge"
type = "required"
versionRange = "[21.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fleecifer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.3,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "fleecifer.mixins.json"
